apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahorro-deployment
  labels:
    app: ahorro-deployment
spec:
  selector:
    matchLabels:
      app: ahorro-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ahorro-deployment
    spec:
      containers:
        - name: ahorro-service
          image: nitroryder/ahorro-service
          ports:
            - containerPort: 8090