apiVersion: apps/v1
kind: Deployment
metadata:
  name: credito-deployment
  labels:
    app: credito-deployment
spec:
  selector:
    matchLabels:
      app: credito-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: credito-deployment
    spec:
      containers:
        - name: credito-service
          image: nitroryder/credito-service
          ports:
            - containerPort: 8092