apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingesolab2-front-end-deployment
  labels:
    app: tingesolab2-front-end-deployment
spec:
  selector:
    matchLabels:
      app: tingesolab2-front-end-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: tingesolab2-front-end-deployment
    spec:
      containers:
        - name: tingesolab2-front-end
          image: nitroryder/tingesolab2-front-end:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: tingesolab2-front-end-service
  labels:
    app: tingesolab2-front-end
spec:
  selector:
    app: tingesolab2-front-end-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer