apiVersion: apps/v1
kind: Deployment
metadata:
  name: seguimiento-deployment
  labels:
    app: seguimiento-deployment
spec:
  selector:
    matchLabels:
      app: seguimiento-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: seguimiento-deployment
    spec:
      containers:
        - name: seguimiento-service
          image: nitroryder/seguimiento-service
          ports:
            - containerPort: 8096