apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuario-deployment
  labels:
    app: usuario-deployment
spec:
  selector:
    matchLabels:
      app: usuario-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: usuario-deployment
    spec:
      containers:
        - name: usuario-service
          image: nitroryder/usuario-service
          ports:
            - containerPort: 8093