server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/NitroRyder/TingesoEntrega2
          search-paths: Microservicios
  application:
    name: config-service