server:
  port: 8030
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
            url: https://github.com/NitroRyder/TingesoEntrega2
            search-paths: Microservicios/config-data
    application:
      name: config-service